services:
    _defaults:
        autowire: true

    Rector\NAI\:
        resource: ../../src
        exclude: ../../src/{DependencyInjection/AppKernel.php}

    Rector\NAI\Git\GitRepository:
        arguments:
            - '%git_name%'
            - '%git_email%'
            - '%branch_name%'

    Rector\NAI\Application\Application:
        arguments:
            - '%workroom_directory%'
            - '%branch_name%'
        public: true

    # 3rd party
    Symplify\PackageBuilder\Parameter\ParameterProvider: ~

    Symfony\Component\Console\Style\SymfonyStyle:
        factory: ['Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory', 'create']

    # Github
    Github\Client:
        factory: ['@Rector\NAI\Github\ClientFactory', 'create']
    Github\Api\Repo: ~
    Github\Api\PullRequest: ~

    League\Flysystem\Adapter\Local:
        arguments: ['%kernel.cache_dir%/github']
    League\Flysystem\Filesystem: ~
    Cache\Adapter\Filesystem\FilesystemCachePool: ~

    League\Flysystem\AdapterInterface:
        alias: League\Flysystem\Adapter\Local

    # Git
    GitWrapper\GitWrapper:
        factory: ['@Rector\NAI\Git\GitWrapperFactory', 'create']
