services:
    _defaults:
        autowire: true

    Rector\NAI\:
        resource: ../../src
        exclude: ../../src/{DependencyInjection/AppKernel.php}

    Rector\NAI\Git\GitRepository:
        arguments:
            - '%git_name%'
            - '%git_email%'
            - '%branch_name%'

    # runners
    Rector\NAI\Runner\EasyCodingStandardRunner:
        arguments: ['%ecs_level%']

    Rector\NAI\Runner\RectorRunner:
        arguments: ['%rector_level%']

    Rector\NAI\Application\Application:
        arguments:
            - '%workroom_directory%'
            - '%branch_name%'
        public: true
        calls:
            # order here = order in processing
            - ['addRunner', ['@Rector\NAI\Runner\EasyCodingStandardRunner']]
            - ['addRunner', ['@Rector\NAI\Runner\RectorRunner']]
            - ['addRunner', ['@Rector\NAI\Runner\PhpUnitRunner']]
